#!/usr/bin/env bash

# Cleanup
rm -f /tmp/screenshot*.png

# Take screenshot
scrot /tmp/screenshot.png

# Pixelate
convert /tmp/screenshot.png \
-scale 10% \
-scale 1000% \
-fill "#282828" \
-colorize 30% \
/tmp/lockscreen.png

# i3Lock
DARK='#332F2E'
BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#FFB300cc'
TEXT='#FCFBDCcc'
WRONG='#880000bb'
VERIFYING='#bb00bbbb'

i3lock \
--image="/tmp/lockscreen.png" \
--insidever-color=$DARK     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$DARK   \
--ringwrong-color=$WRONG     \
\
--inside-color=$DARK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%A, %m %Y"       \

